name: gemini_agent_tools
description: >
  Code generation for tools sections of Gemini REST API.
version: 0.0.3
repository: "https://github.com/konrad1001/gemini_agent_tools"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ">=7.5.9 <9.0.0"
  source_gen: ">=3.0.0 <5.0.0"
  build: ">=3.0.0 <5.0.0"

dev_dependencies:
  build_runner: ^2.3.3

flutter:
